--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KumaaDeveloper/AzusaNightVision
build-by-default: true
branches:
- main
projects:
  AzusaNightVision:
    path: ""
    icon: icon.png
...
