# Configuration for AzusaNightVision plugin

# Interval (in seconds) to check for Night Vision
CheckInterval: 300

# Mode for world selection: "whitelist" or "blacklist"
Mode: "whitelist"

# List of worlds for whitelist/blacklist
Worlds:
  - lobby
  - world